src/nsls2api/api/v1/beamline_api.py, src/nsls2api/models/beamlines.py, src/nsls2api/services/beamline_service.py
Added `beamline\{name}\detectors` endpoint to list detectors for a beamline.  This resolves #19 
The response is of the form 
```
{
"detectors": [
{
"name": "detector1"
},
{
"name": "detector2"
}
],
"count": 2
}
```
We can add more info about detectors as we want in the future
=> Add endpoint to list beamline detectors

.github/workflows/test-production-deployment.yml, src/nsls2api/api/v1/proposal_api.py
I have also removed the workflow trigger on PR and reduced the frequency of the production endpoint testing.
=> Catch Lookup errors for non-existant proposals

src/nsls2api/api/models/beamline_model.py, src/nsls2api/api/models/proposal_model.py, src/nsls2api/services/beamline_service.py
I've added a field `create_ymd_directory_tree` which will globally default to `false` but is set to be `true` for detector (and default) directories.  
The new response from the API is in an attachment in a comment below.
resolves #32
=> Add flag for Y/M/D tree creation

README.md
Add status badge for the GitHub Action that tests the currently deployed production instance (`api.nsls2.bnl.gov`)
=> Add status badge for deployed production instance tests

src/nsls2api/api/v1/proposal_api.py
We were not catching `LookupError`s that were being thrown.  Added try/except logic to mitigate this.
Resolves #42
=> Ensure to catch lookup errors

src/nsls2api/api/v1/beamline_api.py, src/nsls2api/models/beamlines.py, src/nsls2api/services/beamline_service.py, src/nsls2api/services/proposal_service.py
Added the missing SynchWeb user read permissions if the beamline uses the SynchWeb service.
The method of determining if a beamline uses SynchWeb is to look at the `services` field in the beamline document which is a list of services that the beamline uses.  If one exists with the `name` of `synchweb` then we assume that the beamline is using SynchWeb
This resolves #40
=> Add SynchWeb user permission for proposal directories

src/nsls2api/models/proposals.py
Seems that if some fields are missing from the upstream data services then we are not populating them with a default value.  
We should fix the data ingestion pipeline, but to make sure we catch it here I'm adding some default values in the pydantic model. 
Resolves #46
=> Update Proposal model with default values

src/nsls2api/services/proposal_service.py
The error checking for invalid cycle info didn't include a check for commissioning proposals.
=> Fix proposal directories endpoint for commissioning proposals

src/nsls2api/models/proposals.py
This should resolve #43 
There is a proposal with a user with `null` for both names (proposal_id = 300551) which is only in cycle 2016-1
=> Make the first and last name optional for a user (to match PASS behaviour)

src/nsls2api/api/models/stats_model.py, src/nsls2api/api/v1/stats_api.py
As an added check in ensuring we are syncing correctly, I have added the total proposals per NSLS-II cycle in addtion to just the total number of proposals.
=> Update stats API to include NSLS2 proposals per cycle

src/nsls2api/services/background_service.py, src/nsls2api/services/facility_service.py, src/nsls2api/services/proposal_service.py
Some small changes bundled together.
* Improved the worker function names to be clearer what they are doing.
* When we sync the cycle list, also populate it with the allocated proposals for that cycle
* and most importantly, now I am sure by background worker process is working, change the chatty info log messages to debug.
=> A number of small improvements to PASS synchronization

src/nsls2api/infrastructure/config.py
Another attempt to make the dev site start up without having to specify the slack config vars
=> Make slack config env vars optional

src/nsls2api/api/models/proposal_model.py, src/nsls2api/api/v1/proposal_api.py, src/nsls2api/infrastructure/config.py
In the old API there was an endpoint that gave the group name and the list of usernames.  In the new version the groupname was accidentally omitted.   This is something that the powershell script that populates the groups relies on. 
Also, included a small fix to allow startup even if we are missing variables from our `.env` file.
=> Add groupname field to username endpoint response

src/nsls2api/services/beamline_service.py
After reflection with @mrakitin and @danielballan, we've determined that it should be broadly safe to give nsl2data write access to these directories.
The initial motivation for this is that under POSIX ACLs the default ACL for owner that gets inherited by newly created files does not allow them to be writable for softioc.
=> Give nsls2data write for detector directories

src/nsls2api/services/proposal_service.py
When writing tests for [start-experiment](https://github.com/Kezzsim/start-experiment/tree/docs-and-tests) we realized it is not possible to authenticate and associate with an account. This will let us add a string in the http post `add_specific_user` that correlates to an actual user's username and pulls information about them from the people api.
=> 🫂 Add a real person to a proposal so we can test authenticating 

src/nsls2api/api/models/proposal_model.py, src/nsls2api/api/v1/beamline_api.py, src/nsls2api/cli/auth.py, src/nsls2api/models/beamlines.py, src/nsls2api/services/beamline_service.py
For some unknown reason, the name I gave the endpoint to generate the directory skeleton layout for a given beamline is called `proposal-directory-skeleton` which does not make sense.  I've added a new endpoint `directory-skeleton` and deprecated the `proposal-directory-skeleton` endpoint with a view to removing in the future. 
Also separated out the response model for the proposal directories from the beamline directory skeleton.
=> Cleanup endpoint for beamline skeleton

src/nsls2api/api/v1/admin_api.py
`use_real_people` boolean was still appearing in the docs when it has since been replaced with `add_specific_user`
This corrects that.
=> 🚮 Clean up old variables in the docs

integration-tests/check_all_beamlines.http
The `TST` beamline was missing from the list of simple endpoint checks.
=> Add TST beamline to endpoint tests

src/nsls2api/services/facility_service.py, src/nsls2api/services/sync_service.py
Some minor changes added while debugging the dataadmin syncing issues, namely;
* Added `last_updated` timestamp to facility documents
* Added warning message when facility document does not specify a `data_admin_group`
* Added flag to skip Beamline data admin syncing (intentionally not exposed upstream on the endpoint).
=> Some improvements to logging output 

src/nsls2api/api/v1/beamline_api.py, src/nsls2api/services/beamline_service.py
This PR:
* Adds the ability to set all detector/instrument fields from the API
* Adds the ability to delete detectors/instruments via the API
* Removes a redundant copy of `add_service` which crept in
=> Updates to add_detector endpoint

src/nsls2api/services/sync_service.py
Also revert recent 'fix' that removed the instrument list from the SAF
=> Make sure proposal and saf instrument lists are unique

src/nsls2api/api/models/stats_model.py, src/nsls2api/api/v1/facility_api.py, src/nsls2api/api/v1/jobs_api.py, src/nsls2api/api/v1/proposal_api.py, src/nsls2api/api/v1/stats_api.py, src/nsls2api/services/background_service.py, src/nsls2api/services/pass_service.py, src/nsls2api/services/proposal_service.py, src/nsls2api/services/sync_service.py
Exposed the facility name to various functions and endpoints.   
I have not extensively tested this yet.
=> Add facility to sync functions

src/nsls2api/services/pass_service.py, src/nsls2api/services/sync_service.py
* default of nsls2 results in PASS API exception: httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://passservices.bnl.gov/....../NSLS-II/300047/null'
=> fix missing facility specification

src/nsls2api/api/v1/jobs_api.py, src/nsls2api/services/background_service.py, src/nsls2api/services/sync_service.py
Fix pass_service calls that must have the correct facility
=> Fix pass service calls with facility

README.md, src/nsls2api/services/helpers.py, src/nsls2api/services/sync_service.py
This was originally done to support the UPS integration effort, as it requires authentication on its endpoints.  But, I think that it's worth bringing into the main codebase as we may need this feature in the future and it does no harm.
I am also sneaking in some small changes to the README to provide instructions on running the code formatter and linting tools.
=> Add auth for httpx client

src/nsls2api/services/bnlpeople_service.py
* logging to ensure exceptions go into logs
* return None to prevent failure of entire sync processes - though this leaves the person referenced out of the proposal being synchronized
=> bnlpeople query failures fail more gracefully

src/nsls2api/services/beamline_service.py, src/nsls2api/services/proposal_service.py
This PR makes the ACLs for the top-level of the proposal, and for the skeleton directories, match more closely to eachother so that it is easier to compare and understand how they relate. It also fixes a couple of bugs.
* Remove plain-old `softioc` access for skeleton directories - this account should be unused, and has no access into the proposal directory at all anyway (so this ACL was itself unused)
* If a bluesky service account exists for a beamline, give it read-access to the proposal. Previously access was only given to the skeleton directories, so this account would not have been able to see into the proposal. (These accounts are not used yet)
* Make the `softioc-tla` and `workflow-tla` accounts required for the skeleton directories, since they are already required for the …
=> Make top-level and skeleton directory ACLs better match

src/nsls2api/services/helpers.py
Currently, the SOCKS proxy settings in `.env` are not applied to the client used for access to PASS. This PR changes this, so these settings are applied as expected.
=> Use SOCKS proxy settings for PASS client

src/nsls2api/api/models/proposal_model.py, src/nsls2api/api/v1/proposal_api.py, src/nsls2api/services/pass_service.py, src/nsls2api/services/proposal_service.py
This PR adds in support to deal with LBMS facilities commissioning proposals.
There are a number of places that this code can be improved by removing hard coded values for the PASS IDs for the respective commissioning proposal types (I've created an issue #146 )
Testing on my local dev instance... 
http://127.0.0.1:8000/v1/proposals/commissioning?facility=lbms
```json
{
"count": 0,
"commissioning_proposals": [],
"beamline": null,
"facility": "lbms"
}
```
http://127.0.0.1:8000/v1/proposals/commissioning?facility=nsls2
```json
{
"count": 30,
"commissioning_proposals": [
"311955",
"312922",
"311272",
...
<truncated list>
...
"312051",
"313772"
],
"beamline": null,
"facility": "nsls2"
}
```
http://127.0.0.1:8000/v1/proposals/commissioning?facility=cfn
```json
{
"count": 0, …
```
=> Add LBMS commissioning proposal support

integration-tests/check_all_beamlines.http, src/nsls2api/infrastructure/config.py, src/nsls2api/services/slack_service.py
This PR addresses a few small issues found while testing on BMM.  
- Add back in admin credentials to allow to invite users to the nsls2 slack workspace
- If all the users are already in the channel, then don't try to invite a blank list.
- Tolerate expected errors thrown by Slack API when we can't find a user by email yet.
As an unconnected commit, I'm also correcting the http response code for non-existent beamlines.
=> Bug fixes for Slack channel creation workflow

src/nsls2api/api/v1/stats_api.py
The `/stats` endpoint is currently broken - hopefully this fixes it.
=> Fix /stats endpoint

src/nsls2api/api/v1/proposal_api.py
Only allow admins to create slack channels
=> Add admin role validation dependency to Slack channels creation endpoint

src/nsls2api/api/v1/stats_api.py
Add some error handling for when the underlying database does not contain the cycle details for a facility - this usually happens when the synchronization is not working. 
There was also a bug in the code that wasn't actually getting the list of cycles for lbms facility but getting them for nsls2 instead.
=> Fix problem when LBMS database has not synchronized

src/nsls2api/services/slack_service.py
For users that need to be invited in the NSLS2 workspace, they will not appear as a member of the channel that they are invited into until they accept the invite, but for any additional channels that we add the user to they will appear instantly.  In order to avoid confusion this PR intends to, once the new user is invited to the workspace, we then also add it to the channel at the same time.
=> Make the invitation of slack users more robust

requirements-dev.txt, requirements.txt, src/nsls2api/api/v1/beamline_api.py, src/nsls2api/api/v1/stats_api.py, src/nsls2api/cli/__init__.py, src/nsls2api/cli/admin.py, src/nsls2api/cli/api.py, src/nsls2api/cli/auth.py, src/nsls2api/cli/beamline.py, src/nsls2api/cli/cli.py, src/nsls2api/cli/environment.py, src/nsls2api/cli/facility.py, src/nsls2api/cli/proposal.py, src/nsls2api/cli/settings.py, src/nsls2api/cli/utils/api.py, src/nsls2api/cli/utils/cli_helpers.py, src/nsls2api/cli/utils/console.py, src/nsls2api/models/proposals.py, src/nsls2api/services/slack_service.py
This is adding the initial 'experimental' `nsls2api` cli tool. 
It also adds a new endpoint of `/v1/beamlines` to return all the beamlines so that we can have the command `nsls2api beamline list`. 
To test the cli, first checkout this branch and `cd` to it.  Then if you have `uv` installed you should be able to simply run 
```
uv run nsls2api
```
Which should show the help screen. 
Other commands to try are:
- `uv run nsls2api api status` 
- `uv run nsls2api api metrics`
- `uv run nsls2api env show` -> Displays the current environment 
- `uv run nsls2api env switch dev` -> switch to look at the api-dev.nsls2.bnl.gov instance
- `uv run beamline view bmm` -> details on BMM
- `uv run nsls2api beamline detectors bmm` -> Detectors for BMM
- `uv run nsls2api proposal view 316832` -> Details on …
=> Add experimental CLI tool

src/nsls2api/api/v1/proposal_api.py, src/nsls2api/cli/proposal.py, src/nsls2api/services/proposal_service.py
This resolves #162 
This adds an endpoint to lookup a proposal by using the `saf_id` with a url of `/v1/proposal/saf/{saf_id}`.
To test the cli, first checkout this branch and cd to it. Then if you have uv installed you should be able to simply run
- `uv run nsls2api proposal view 316985` 
- `uv run nsls2api proposal view 315735 --saf` 
Both these commands should show the same info for proposal 316985
=> API endpoint and CLI functionality to lookup a proposal using SAF ID

pyproject.toml, requirements.in, requirements.txt, src/nsls2api/api/v1/stats_api.py, src/nsls2api/cli/cli.py, src/nsls2api/version.py
The method I was using for dynamic versioning didn't seem to be working reliably.  This PR changes the method to use a different package for version determination. 
This also fixed an issue with the CLI where just running the command with no command and a flag would return an error (i.e. the `--version` would always fail)
If you checkout the branch, cd into it and then type `uv run nsls2api --version` should return the version.
Also, if you stand up the server, then the `/v1/about` endpoint should also return the version.
=> Fix versioning

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-publish.yml, .github/workflows/test-dev-deployment.yml, .github/workflows/test-production-deployment.yml
Apply recommended hardening steps including:
- pinning to a SHA any actions used
- not persisting the read token on checkout
- setting the default permissions to read-only
=> CI: Harden GHA configuration

.github/workflows/data-consistency-workflow.yml, README.md, integration-tests/check_beamlines_differences.http
This check/test checks the differences in the output for the `/v1/beamlines` endpoint on both the development and production API instances.  
This hopefully will pickup and highlight any database data inconsistencies that may creep in.
=> Add beamline difference check

.github/workflows/ci.yml, pyproject.toml
As we don't deploy on 3.11 anywhere - remove support for it and make the minimum supported version 3.12
=> Drop support for Python 3.11
